# Generated by Django 5.1.5 on 2025-01-24 01:40

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('weight', models.PositiveIntegerField(blank=True, null=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StatisticsCycleInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cycle_length', models.PositiveIntegerField(blank=True, null=True)),
                ('period_length', models.PositiveIntegerField(blank=True, null=True)),
                ('average_pain_level', models.PositiveIntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], null=True)),
                ('allergies', models.TextField(blank=True, null=True)),
                ('medications', models.TextField(blank=True, null=True)),
                ('health_conditions', models.TextField(blank=True, null=True)),
                ('symptoms', models.CharField(blank=True, choices=[('1', 'Ból brzucha'), ('2', 'Ból pleców'), ('3', 'Ból nóg'), ('4', 'Ból w klatce piersiowej'), ('5', 'Ból głowy'), ('6', 'Ból ramion'), ('7', 'Kłucie w pochwie'), ('8', 'Podwyższona temperatura ciała'), ('9', 'Obniżona temperatura ciała'), ('10', 'Biegunka'), ('11', 'Zaparcia'), ('12', 'Zgaga'), ('13', 'Obrzęk'), ('14', 'Trądzik'), ('15', 'Dusznosc'), ('16', 'Wahania nastroju'), ('17', 'Wzdęcia'), ('18', 'Krwawienie z odbytnicy'), ('19', 'Zmęczenie')], max_length=255)),
                ('mood', models.CharField(blank=True, choices=[('1', 'Szczęście'), ('2', 'Entuzjazm'), ('3', 'Ekscytacja'), ('4', 'Smutek'), ('5', 'Rozpacz'), ('6', 'Lęk'), ('7', 'Irytacja'), ('8', 'Gniew'), ('9', 'Radość'), ('10', 'Smutek'), ('11', 'Strach'), ('12', 'Złość'), ('13', 'Wstręt'), ('14', 'Smutek'), ('15', 'Panika')], max_length=255)),
                ('date', models.DateField(blank=True, null=True)),
                ('event', models.TextField(blank=True, null=True)),
                ('user_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='period_app.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='HealthAndCycleFormModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_day_of_cycle', models.DateField(blank=True, null=True)),
                ('cycle_length', models.PositiveIntegerField(blank=True, null=True)),
                ('period_length', models.PositiveIntegerField(blank=True, null=True)),
                ('last_period_start', models.DateField(blank=True, null=True)),
                ('average_pain_level', models.PositiveIntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], null=True)),
                ('menstruation_phase_start', models.DateField(blank=True, null=True)),
                ('menstruation_phase_end', models.DateField(blank=True, null=True)),
                ('follicular_phase_start', models.DateField(blank=True, null=True)),
                ('follicular_phase_end', models.DateField(blank=True, null=True)),
                ('ovulation_phase_start', models.DateField(blank=True, null=True)),
                ('ovulation_phase_end', models.DateField(blank=True, null=True)),
                ('luteal_phase_start', models.DateField(blank=True, null=True)),
                ('luteal_phase_end', models.DateField(blank=True, null=True)),
                ('allergies', models.TextField(blank=True, null=True)),
                ('medications', models.TextField(blank=True, null=True)),
                ('health_conditions', models.TextField(blank=True, null=True)),
                ('pregnancy_start', models.DateField(blank=True, null=True)),
                ('pregnancy_end', models.DateField(blank=True, null=True)),
                ('current_cycle_day', models.PositiveIntegerField(blank=True, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('event', models.TextField(blank=True, null=True)),
                ('daily_symptoms', models.CharField(blank=True, choices=[('1', 'Ból brzucha'), ('2', 'Ból pleców'), ('3', 'Ból nóg'), ('4', 'Ból w klatce piersiowej'), ('5', 'Ból głowy'), ('6', 'Ból ramion'), ('7', 'Kłucie w pochwie'), ('8', 'Podwyższona temperatura ciała'), ('9', 'Obniżona temperatura ciała'), ('10', 'Biegunka'), ('11', 'Zaparcia'), ('12', 'Zgaga'), ('13', 'Obrzęk'), ('14', 'Trądzik'), ('15', 'Dusznosc'), ('16', 'Wahania nastroju'), ('17', 'Wzdęcia'), ('18', 'Krwawienie z odbytnicy'), ('19', 'Zmęczenie')], max_length=255)),
                ('daily_mood', models.CharField(blank=True, choices=[('1', 'Szczęście'), ('2', 'Entuzjazm'), ('3', 'Ekscytacja'), ('4', 'Smutek'), ('5', 'Rozpacz'), ('6', 'Lęk'), ('7', 'Irytacja'), ('8', 'Gniew'), ('9', 'Radość'), ('10', 'Smutek'), ('11', 'Strach'), ('12', 'Złość'), ('13', 'Wstręt'), ('14', 'Smutek'), ('15', 'Panika')], max_length=255)),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='period_app.userprofile')),
            ],
        ),
    ]
