# Generated by Django 5.1.5 on 2025-01-20 00:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('period_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='birth_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='HealthAndCycleFormModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_day_of_cycle', models.DateField(blank=True, null=True)),
                ('cycle_length', models.PositiveIntegerField(blank=True, null=True)),
                ('period_length', models.PositiveIntegerField(blank=True, null=True)),
                ('last_period_start', models.DateField(blank=True, null=True)),
                ('average_pain_level', models.PositiveIntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], null=True)),
                ('menstruation_phase_start', models.DateField(blank=True, null=True)),
                ('menstruation_phase_end', models.DateField(blank=True, null=True)),
                ('follicular_phase_start', models.DateField(blank=True, null=True)),
                ('follicular_phase_end', models.DateField(blank=True, null=True)),
                ('ovulation_phase_start', models.DateField(blank=True, null=True)),
                ('ovulation_phase_end', models.DateField(blank=True, null=True)),
                ('luteal_phase_start', models.DateField(blank=True, null=True)),
                ('luteal_phase_end', models.DateField(blank=True, null=True)),
                ('allergies', models.TextField(blank=True, null=True)),
                ('medications', models.TextField(blank=True, null=True)),
                ('health_conditions', models.TextField(blank=True, null=True)),
                ('symptoms', models.CharField(blank=True, choices=[('1', 'Ból brzucha'), ('2', 'Ból pleców'), ('3', 'Ból nóg'), ('4', 'Ból w klatce piersiowej'), ('5', 'Ból głowy'), ('6', 'Ból ramion'), ('7', 'Kłucie w pochwie'), ('8', 'Podwyższona temperatura ciała'), ('9', 'Obniżona temperatura ciała'), ('10', 'Biegunka'), ('11', 'Zaparcia'), ('12', 'Zgaga'), ('13', 'Obrzęk'), ('14', 'Trądzik'), ('15', 'Dusznica'), ('16', 'Wahania nastroju'), ('17', 'Wzdęcia'), ('18', 'Krwawe stolce'), ('19', 'Zmęczenie')], max_length=255)),
                ('mood', models.CharField(blank=True, choices=[('1', 'Szczęście'), ('2', 'Entuzjazm'), ('3', 'Ekscytacja'), ('4', 'Smutek'), ('5', 'Rozpacz'), ('6', 'Lęk'), ('7', 'Irytacja'), ('8', 'Gniew'), ('9', 'Radość'), ('10', 'Smutek'), ('11', 'Strach'), ('12', 'Złość'), ('13', 'Wstręt'), ('14', 'Smutek'), ('15', 'Panika')], max_length=255)),
                ('user_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='period_app.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='StatisticsCycleInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cycle_length', models.PositiveIntegerField(blank=True, null=True)),
                ('period_length', models.PositiveIntegerField(blank=True, null=True)),
                ('average_pain_level', models.PositiveIntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], null=True)),
                ('allergies', models.TextField(blank=True, null=True)),
                ('medications', models.TextField(blank=True, null=True)),
                ('health_conditions', models.TextField(blank=True, null=True)),
                ('symptoms', models.CharField(blank=True, choices=[('1', 'Ból brzucha'), ('2', 'Ból pleców'), ('3', 'Ból nóg'), ('4', 'Ból w klatce piersiowej'), ('5', 'Ból głowy'), ('6', 'Ból ramion'), ('7', 'Kłucie w pochwie'), ('8', 'Podwyższona temperatura ciała'), ('9', 'Obniżona temperatura ciała'), ('10', 'Biegunka'), ('11', 'Zaparcia'), ('12', 'Zgaga'), ('13', 'Obrzęk'), ('14', 'Trądzik'), ('15', 'Dusznica'), ('16', 'Wahania nastroju'), ('17', 'Wzdęcia'), ('18', 'Krwawe stolce'), ('19', 'Zmęczenie')], max_length=255)),
                ('mood', models.CharField(blank=True, choices=[('1', 'Szczęście'), ('2', 'Entuzjazm'), ('3', 'Ekscytacja'), ('4', 'Smutek'), ('5', 'Rozpacz'), ('6', 'Lęk'), ('7', 'Irytacja'), ('8', 'Gniew'), ('9', 'Radość'), ('10', 'Smutek'), ('11', 'Strach'), ('12', 'Złość'), ('13', 'Wstręt'), ('14', 'Smutek'), ('15', 'Panika')], max_length=255)),
                ('user_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cycle_info', to='period_app.userprofile')),
            ],
        ),
    ]
