# Generated by Django 5.1.5 on 2025-01-21 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('period_app', '0002_userprofile_birth_date_healthandcycleformmodel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthandcycleformmodel',
            name='pregnancy_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='healthandcycleformmodel',
            name='pregnancy_start',
            field=models.DateField(blank=True, null=True),
        ),
    ]
