# Generated by Django 5.1.5 on 2025-01-24 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('period_app', '0002_alter_userprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthandcycleformmodel',
            name='menstruation_days',
            field=models.JSONField(default=list),
        ),
    ]
