# Generated by Django 5.1.5 on 2025-01-25 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('period_app', '0003_healthandcycleformmodel_menstruation_days'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statisticscycleinfo',
            name='mood',
        ),
        migrations.RemoveField(
            model_name='statisticscycleinfo',
            name='symptoms',
        ),
        migrations.AddField(
            model_name='healthandcycleformmodel',
            name='recorded_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Recorded At'),
        ),
        migrations.AddField(
            model_name='statisticscycleinfo',
            name='current_cycle_day',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statisticscycleinfo',
            name='daily_mood',
            field=models.CharField(blank=True, choices=[('1', 'Szczęście'), ('2', 'Entuzjazm'), ('3', 'Ekscytacja'), ('4', 'Smutek'), ('5', 'Rozpacz'), ('6', 'Lęk'), ('7', 'Irytacja'), ('8', 'Gniew'), ('9', 'Radość'), ('10', 'Smutek'), ('11', 'Strach'), ('12', 'Złość'), ('13', 'Wstręt'), ('14', 'Rozpacz'), ('15', 'Panika')], max_length=255),
        ),
        migrations.AddField(
            model_name='statisticscycleinfo',
            name='daily_symptoms',
            field=models.CharField(blank=True, choices=[('1', 'Ból brzucha'), ('2', 'Ból pleców'), ('3', 'Ból nóg'), ('4', 'Ból w klatce piersiowej'), ('5', 'Ból głowy'), ('6', 'Ból ramion'), ('7', 'Kłucie w pochwie'), ('8', 'Podwyższona temperatura ciała'), ('9', 'Obniżona temperatura ciała'), ('10', 'Biegunka'), ('11', 'Zaparcia'), ('12', 'Zgaga'), ('13', 'Obrzęk'), ('14', 'Trądzik'), ('15', 'Dusznosci'), ('16', 'Wahania nastroju'), ('17', 'Wzdęcia'), ('18', 'Krwawienie zastepcze'), ('19', 'Zmęczenie')], max_length=255),
        ),
        migrations.AddField(
            model_name='statisticscycleinfo',
            name='first_day_of_cycle',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statisticscycleinfo',
            name='last_period_start',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statisticscycleinfo',
            name='menstruation_days',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='statisticscycleinfo',
            name='menstruation_phase_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statisticscycleinfo',
            name='menstruation_phase_start',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statisticscycleinfo',
            name='pregnancy_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statisticscycleinfo',
            name='pregnancy_start',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statisticscycleinfo',
            name='recorded_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Recorded At'),
        ),
        migrations.AlterField(
            model_name='healthandcycleformmodel',
            name='daily_mood',
            field=models.CharField(blank=True, choices=[('1', 'Szczęście'), ('2', 'Entuzjazm'), ('3', 'Ekscytacja'), ('4', 'Smutek'), ('5', 'Rozpacz'), ('6', 'Lęk'), ('7', 'Irytacja'), ('8', 'Gniew'), ('9', 'Radość'), ('10', 'Smutek'), ('11', 'Strach'), ('12', 'Złość'), ('13', 'Wstręt'), ('14', 'Rozpacz'), ('15', 'Panika')], max_length=255),
        ),
        migrations.AlterField(
            model_name='healthandcycleformmodel',
            name='daily_symptoms',
            field=models.CharField(blank=True, choices=[('1', 'Ból brzucha'), ('2', 'Ból pleców'), ('3', 'Ból nóg'), ('4', 'Ból w klatce piersiowej'), ('5', 'Ból głowy'), ('6', 'Ból ramion'), ('7', 'Kłucie w pochwie'), ('8', 'Podwyższona temperatura ciała'), ('9', 'Obniżona temperatura ciała'), ('10', 'Biegunka'), ('11', 'Zaparcia'), ('12', 'Zgaga'), ('13', 'Obrzęk'), ('14', 'Trądzik'), ('15', 'Dusznosci'), ('16', 'Wahania nastroju'), ('17', 'Wzdęcia'), ('18', 'Krwawienie zastepcze'), ('19', 'Zmęczenie')], max_length=255),
        ),
    ]
