# Generated by Django 5.1.5 on 2025-01-29 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('period_app', '0007_rename_health_conditions_healthandcycleformmodel_health_condition_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthandcycleformmodel',
            name='daily_mood',
            field=models.CharField(blank=True, choices=[('Szczęście', 'Szczęście'), ('Entuzjazm', 'Entuzjazm'), ('Ekscytacja', 'Ekscytacja'), ('Smutek', 'Smutek'), ('Rozpacz', 'Rozpacz'), ('Lęk', 'Lęk'), ('Irytacja', 'Irytacja'), ('Gniew', 'Gniew'), ('Radość', 'Radość'), ('Placz', 'Placz'), ('Strach', 'Strach'), ('Złość', 'Złość'), ('Wstręt', 'Wstręt'), ('Rozpacz', 'Rozpacz'), ('Panika', 'Panika')], max_length=255),
        ),
        migrations.AlterField(
            model_name='healthandcycleformmodel',
            name='daily_symptoms',
            field=models.CharField(blank=True, choices=[('Ból brzucha', 'Ból brzucha'), ('Ból pleców', 'Ból pleców'), ('Ból nóg', 'Ból nóg'), ('Ból w klatce piersiowej', 'Ból w klatce piersiowej'), ('Ból głowy', 'Ból głowy'), ('Ból ramion', 'Ból ramion'), ('Kłucie w pochwie', 'Kłucie w pochwie'), ('Podwyższona temperatura ciała', 'Podwyższona temperatura ciała'), ('Obniżona temperatura ciała', 'Obniżona temperatura ciała'), ('Biegunka', 'Biegunka'), ('Zaparcia', 'Zaparcia'), ('Zgaga', 'Zgaga'), ('Obrzęk', 'Obrzęk'), ('Trądzik', 'Trądzik'), ('Dusznosci', 'Dusznosci'), ('Wahania nastroju', 'Wahania nastroju'), ('Wzdęcia', 'Wzdęcia'), ('Krwawienie zastepcze', 'Krwawienie zastepcze'), ('Zmęczenie', 'Zmęczenie')], max_length=255),
        ),
        migrations.AlterField(
            model_name='statisticscycleinfo',
            name='daily_mood',
            field=models.CharField(blank=True, choices=[('Szczęście', 'Szczęście'), ('Entuzjazm', 'Entuzjazm'), ('Ekscytacja', 'Ekscytacja'), ('Smutek', 'Smutek'), ('Rozpacz', 'Rozpacz'), ('Lęk', 'Lęk'), ('Irytacja', 'Irytacja'), ('Gniew', 'Gniew'), ('Radość', 'Radość'), ('Placz', 'Placz'), ('Strach', 'Strach'), ('Złość', 'Złość'), ('Wstręt', 'Wstręt'), ('Rozpacz', 'Rozpacz'), ('Panika', 'Panika')], max_length=255),
        ),
        migrations.AlterField(
            model_name='statisticscycleinfo',
            name='daily_symptoms',
            field=models.CharField(blank=True, choices=[('Ból brzucha', 'Ból brzucha'), ('Ból pleców', 'Ból pleców'), ('Ból nóg', 'Ból nóg'), ('Ból w klatce piersiowej', 'Ból w klatce piersiowej'), ('Ból głowy', 'Ból głowy'), ('Ból ramion', 'Ból ramion'), ('Kłucie w pochwie', 'Kłucie w pochwie'), ('Podwyższona temperatura ciała', 'Podwyższona temperatura ciała'), ('Obniżona temperatura ciała', 'Obniżona temperatura ciała'), ('Biegunka', 'Biegunka'), ('Zaparcia', 'Zaparcia'), ('Zgaga', 'Zgaga'), ('Obrzęk', 'Obrzęk'), ('Trądzik', 'Trądzik'), ('Dusznosci', 'Dusznosci'), ('Wahania nastroju', 'Wahania nastroju'), ('Wzdęcia', 'Wzdęcia'), ('Krwawienie zastepcze', 'Krwawienie zastepcze'), ('Zmęczenie', 'Zmęczenie')], max_length=255),
        ),
    ]
