# Generated by Django 5.1.5 on 2025-01-29 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('period_app', '0008_alter_healthandcycleformmodel_daily_mood_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthandcycleformmodel',
            name='daily_mood',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='healthandcycleformmodel',
            name='daily_symptoms',
            field=models.JSONField(default=list),
        ),
    ]
